package com.api.formSync.util;

public enum ErrorCode {
    DUPLICATE_EMAIL,
    DISABLED,
    LOCKED,
    MISSING_TOKEN, EXPIRED_TOKEN, INVALID_TOKEN, NONE, USER_NOT_FOUND, CONFLICT, MISSING_COOKIE, UNAUTHORIZED
}
